# Refactored from Code Base by https://github.com/ubicomplab/rPPG-Toolbox
BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 6
  EPOCHS: 25
  LR: 0.0002 # 9e-3
  # MODEL_FILE_NAME: ResNet3D-50_NeuralTextures_pretrained_SGD_LR=0.0001_LRreducer_16_frames
  # MODEL_FILE_NAME: Test_ResNet3D_NeuralTextures_pretrained_SGD_LR=0.00001_LRreducer_16_frames
  MODEL_FILE_NAME: Xception_Face2Face_nopretrain_ADAM_LR=0.0002_batch_6_real_paths_full_dataset_testdata
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: NeuralTextures   # as folder name
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/SCAMPS/RawData/Train"          # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 224
        W: 224
VALID:
  DATA:
    FS: 30
    DATASET: NeuralTextures   # as folder name
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/SCAMPS/RawData/Val"          # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: False
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 224
        W: 224
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: Face2Face
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/PURE/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']         #if use physnet, should be DiffNormalized
      LABEL_TYPE: Raw
      DO_CHUNK: True
      CHUNK_LENGTH: 32                 #only support for factor of 512
      CROP_FACE:
        DO_CROP_FACE: True
        BACKEND: 'HC'    # HC for Haar Cascade, RF for RetinaFace
        USE_LARGE_FACE_BOX: False
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 32
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 224
        W: 224
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp/logs
MODEL:
  DROP_RATE: 0.2
  NAME: Xception
  PHYSNET:
    FRAME_NUM: 32
INFERENCE:
  BATCH_SIZE: 6
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  # MODEL_PATH: ""
  MODEL_PATH: "/vol/research/DeepFakeDet/rPPG-Toolbox/runs/exp/logs/Xception_NeuralTextures_nopretrain_ADAM_LR=0.0002_batch_6_real_paths_full_dataset/PreTrainedModels/Xception_NeuralTextures_nopretrain_ADAM_LR=0.0002_batch_6_real_paths_full_dataset_Epoch12.pth"